AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - spec/**/*.rb
    - vendor/**/*

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false
