#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'optparse'

lib_path = Pathname.new(__dir__).join('..', 'lib').expand_path
$LOAD_PATH.unshift(lib_path.to_s)

require 'trans'

options = {}

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: mkv-transcoder [options]'

  opts.on('-c', '--config [CONFIGURATION_FILE]', 'Path to configuration file')
end

parser.parse!(into: options)

configuration_path = options.fetch(:config) do
  Pathname.new('~').join('.config', 'trans', 'config.yml')
end

configuration = Trans::ConfigurationFile.load(Pathname(configuration_path))
transcoded_movies = configuration.destination_directory.completed

configuration.configured.each do |config|
  if transcoded_movies.include?(config.source.movie)
    # TODO: messaging
    next
  end

  transcoder = Trans::Transcoder.new(
    config,
    source_path: configuration.locations.source,
    destination_path: configuration.locations.destination
  )

  transcoder.transcode
end
